/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#002113',
        'outline-variant': '#43474d',
        'inverse-primary': '#49607e',
        'on-secondary-fixed-variant': '#003ea8',
        'on-tertiary-fixed-variant': '#005236',
        'surface-variant': '#323537',
        'surface-container-high': '#272a2c',
        'on-surface': '#e0e3e5',
        'primary-fixed-dim': '#b0c8eb',
        'inverse-on-surface': '#2d3133',
        primary: '#b0c8eb',
        outline: '#8e9198',
        'on-secondary-container': '#cdd7ff',
        background: '#101415',
        'on-background': '#e0e3e5',
        'on-error': '#690005',
        tertiary: '#4edea3',
        'on-tertiary-container': '#009e6d',
        'surface-container': '#1d2022',
        'primary-container': '#0a2540',
        'surface-container-highest': '#323537',
        'surface-container-low': '#191c1e',
        'on-primary-fixed': '#001c37',
        'tertiary-fixed': '#6ffbbe',
        'primary-fixed': '#d2e4ff',
        'on-error-container': '#ffdad6',
        'on-primary': '#19324d',
        surface: '#101415',
        'inverse-surface': '#e0e3e5',
        'secondary-fixed': '#dbe1ff',
        'secondary-container': '#0053db',
        'tertiary-fixed-dim': '#4edea3',
        'surface-tint': '#b0c8eb',
        'on-surface-variant': '#c4c6ce',
        error: '#ffb4ab',
        'surface-container-lowest': '#0b0f10',
        'on-secondary-fixed': '#00174b',
        'on-secondary': '#002a78',
        secondary: '#b4c5ff',
        'surface-dim': '#101415',
        'surface-bright': '#363a3b',
        'on-primary-fixed-variant': '#314865',
        'tertiary-container': '#002a1a',
        'error-container': '#93000a',
        'on-tertiary': '#003824',
        'secondary-fixed-dim': '#b4c5ff',
        'on-primary-container': '#768dad',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        xs: '8px',
        gutter: '20px',
        base: '4px',
        xl: '32px',
        md: '16px',
        sm: '12px',
        lg: '24px',
        margin: '40px',
      },
      fontFamily: {
        'body-md': ['Inter'],
        'label-sm': ['JetBrains Mono'],
        'headline-md': ['Inter'],
        'headline-lg': ['Inter'],
        'data-tabular': ['JetBrains Mono'],
        'body-lg': ['Inter'],
        'display-lg': ['Inter'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'data-tabular': ['13px', { lineHeight: '1.2', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      animation: {
        'fade-in': 'fadeIn 0.4s ease-out',
        'slide-up': 'slideUp 0.4s ease-out',
        'slide-down': 'slideDown 0.4s ease-out',
        'scale-in': 'scaleIn 0.35s ease-out',
        'slide-left': 'slideLeft 0.4s ease-out',
        'slide-right': 'slideRight 0.4s ease-out',
        'shimmer': 'shimmer 2s infinite linear',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { opacity: '0', transform: 'translateY(16px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideDown: { '0%': { opacity: '0', transform: 'translateY(-16px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        scaleIn: { '0%': { opacity: '0', transform: 'scale(0.95)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        slideLeft: { '0%': { opacity: '0', transform: 'translateX(12px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        slideRight: { '0%': { opacity: '0', transform: 'translateX(-12px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        pulseSoft: { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.7' } },
      },
    },
  },
  plugins: [],
};
